(function(root){
  'use strict';
  const ID=/^[a-z][a-z0-9_-]*$/;
  function fail(file,message){throw new Error(`${file}: ${message}`)}
  function object(value,file,label){if(!value||typeof value!=='object'||Array.isArray(value))fail(file,`${label} must be an object`)}
  function array(value,file,label){if(!Array.isArray(value))fail(file,`${label} must be an array`)}
  function ids(items,file,label){array(items,file,label);const seen=new Set();for(const item of items){object(item,file,`${label} item`);if(!ID.test(item.id||''))fail(file,`${label} has invalid id "${item.id}"`);if(seen.has(item.id))fail(file,`${label} has duplicate id "${item.id}"`);seen.add(item.id)}return seen}
  function index(items){return Object.fromEntries(items.map(item=>[item.id,item]))}
  function deepFreeze(value){if(value&&typeof value==='object'&&!Object.isFrozen(value)){Object.freeze(value);Object.values(value).forEach(deepFreeze)}return value}
  function build(raw){
    if(raw?.maps?.maps)for(const map of raw.maps.maps){if(!(Number.isFinite(map?.startingCurrency)&&map.startingCurrency>=0))fail('maps.json',`${map?.id||'map'} needs a non-negative startingCurrency`);if(map.iceShield){const shield=map.iceShield;object(shield,'maps.json',`${map.id}.iceShield`);if(!ID.test(shield.id||''))fail('maps.json',`${map.id}.iceShield has invalid id`);if(!Number.isInteger(shield.firstWave)||shield.firstWave<1)fail('maps.json',`${map.id}.iceShield needs a positive firstWave`);if(!(Number.isFinite(shield.spawnChance)&&shield.spawnChance>=0&&shield.spawnChance<=1))fail('maps.json',`${map.id}.iceShield spawnChance must be between 0 and 1`);object(shield.shieldHitRange,'maps.json',`${map.id}.iceShield.shieldHitRange`);const range=shield.shieldHitRange;if(!Number.isInteger(range.min)||!Number.isInteger(range.max)||range.min!==1||range.max!==5)fail('maps.json',`${map.id}.iceShield shieldHitRange must be exactly 1 through 5`)}}
    if(raw?.towers?.config)for(const key of ['heaterCost','HEATER_BASE_UPGRADE_COST','HEATER_UPGRADE_COST_MULTIPLIER','HEATER_BACKLASH_MAX_HP_PERCENT'])if(!(Number.isFinite(raw.towers.config[key])&&raw.towers.config[key]>0))fail('towers.json',`missing or invalid ${key}`);const heaterRadii=raw?.towers?.config?.HEATER_RADII;if(!Array.isArray(heaterRadii)||heaterRadii.length!==3||heaterRadii.some(radius=>!(Number.isFinite(radius)&&radius>0)))fail('towers.json','HEATER_RADII must contain three positive radii');
    const required=['maps','orbs','towers','achievements','tutorial','waves','difficulties'];
    for(const name of required){object(raw[name],`${name}.json`,'root');if(raw[name].version!==1)fail(`${name}.json`,'unsupported or missing version')}
    const mapIds=ids(raw.maps.maps,'maps.json','maps');
    if(!mapIds.has(raw.maps.defaultMapId))fail('maps.json',`defaultMapId references missing map "${raw.maps.defaultMapId}"`);
    for(const map of raw.maps.maps){const points=ids(map.trackWaypoints,'maps.json',`${map.id}.trackWaypoints`);if(points.size<2)fail('maps.json',`${map.id} needs at least two waypoints`);if(!Number.isInteger(map.totalWaves)||map.totalWaves<1)fail('maps.json',`${map.id} needs a positive totalWaves`);if(!ID.test(map.waveSetId||''))fail('maps.json',`${map.id} has invalid waveSetId`);object(map.theme,'maps.json',`${map.id}.theme`);if(!ID.test(map.theme.id||''))fail('maps.json',`${map.id} has invalid theme ID`);if(map.puddleEffects){object(map.puddleEffects,'maps.json',`${map.id}.puddleEffects`);for(const key of ['snowMultiplier','iceMultiplier'])if(!(Number.isFinite(map.puddleEffects[key])&&map.puddleEffects[key]>0))fail('maps.json',`${map.id}.puddleEffects has invalid ${key}`);if(typeof map.puddleEffects.infoText!=='string'||!map.puddleEffects.infoText)fail('maps.json',`${map.id}.puddleEffects needs infoText`)}if(map.snowMutation){const mutation=map.snowMutation;object(mutation,'maps.json',`${map.id}.snowMutation`);if(!ID.test(mutation.id||''))fail('maps.json',`${map.id}.snowMutation has invalid id`);if(!Number.isInteger(mutation.firstWave)||mutation.firstWave<1)fail('maps.json',`${map.id}.snowMutation needs a positive firstWave`);if(!(Number.isFinite(mutation.spawnChance)&&mutation.spawnChance>=0&&mutation.spawnChance<=1))fail('maps.json',`${map.id}.snowMutation spawnChance must be between 0 and 1`);object(mutation.attackIntervalSeconds,'maps.json',`${map.id}.snowMutation.attackIntervalSeconds`);if(!(Number.isFinite(mutation.attackIntervalSeconds.min)&&Number.isFinite(mutation.attackIntervalSeconds.max)&&mutation.attackIntervalSeconds.min>0&&mutation.attackIntervalSeconds.max>=mutation.attackIntervalSeconds.min))fail('maps.json',`${map.id}.snowMutation has an invalid attack interval`);for(const key of ['resistanceRegenerationSeconds','frozenDurationSeconds'])if(!(Number.isFinite(mutation[key])&&mutation[key]>0))fail('maps.json',`${map.id}.snowMutation has invalid ${key}`)}if(map.unlock?.mapId&&!mapIds.has(map.unlock.mapId))fail('maps.json',`${map.id} unlock references missing map "${map.unlock.mapId}"`);ids(map.entrances,'maps.json',`${map.id}.entrances`);ids(map.endpoints,'maps.json',`${map.id}.endpoints`);if(map.entrances.some(e=>!points.has(e.waypointId))||map.endpoints.some(e=>!points.has(e.waypointId)))fail('maps.json',`${map.id} entrance/endpoint references a missing waypoint`)}
    const tierIds=ids(raw.orbs.normalTiers,'orbs.json','normalTiers'),specialIds=ids(raw.orbs.specialOrbs,'orbs.json','specialOrbs'),bossIds=ids(raw.orbs.bosses,'orbs.json','bosses');
    const orbIds=new Set([...tierIds,...specialIds,...bossIds]);if(orbIds.size!==tierIds.size+specialIds.size+bossIds.size)fail('orbs.json','orb IDs must be globally unique');
    raw.orbs.normalTiers.forEach((tier,i)=>{if(tier.tier!==i)fail('orbs.json',`${tier.id} must have tier ${i}`)});
    const towerIds=ids(raw.towers.towers,'towers.json','towers');raw.towers.towers.forEach(t=>{if(t.specializations)ids(t.specializations,'towers.json',`${t.id}.specializations`)});const flameTower=raw.towers.towers.find(tower=>tower.id==='flame_elephant');if(!flameTower)fail('towers.json','missing flame_elephant');if(flameTower.runtimeType!=='flame'||flameTower.cost!==225||flameTower.shopDescription!=='Burns orbs • Melts Ice Shields • Freeze immune')fail('towers.json','flame_elephant identity, cost, or shop description is invalid');const flameStats=flameTower.baseStats,flameUpgrades=flameTower.upgrades;if(flameStats?.directImpactDamage!==0||flameStats?.burnDuration!==5||flameStats?.burnTickInterval!==1||flameStats?.burnDamagePerTick!==5.67)fail('towers.json','flame_elephant burn stats are invalid');if(flameUpgrades?.maxLevel!==5)fail('towers.json','flame_elephant must have five total levels');
    const difficultyIds=ids(raw.difficulties.difficulties,'difficulties.json','difficulties');for(const id of ['easy','normal','hard'])if(!difficultyIds.has(id))fail('difficulties.json',`missing difficulty "${id}"`);
    const achievementIds=ids(raw.achievements.achievements,'achievements.json','achievements');object(raw.achievements.difficultyRewards,'achievements.json','difficultyRewards');raw.achievements.achievements.forEach(a=>{if(!raw.achievements.difficultyRewards[a.difficulty])fail('achievements.json',`${a.id} has unknown difficulty`);const ref=a.unlockCondition?.towerId||a.unlockCondition?.orbId||a.unlockCondition?.waveId;if(ref&&!towerIds.has(ref)&&!orbIds.has(ref)&&!/^wave_\d+$/.test(ref))fail('achievements.json',`${a.id} references missing ID "${ref}"`)});
    const tutorialIds=ids(raw.tutorial.steps,'tutorial.json','steps'),foundryWaveIds=ids(raw.waves.waves,'waves.json','waves'),frozenWaveIds=ids(raw.waves.frozenWaves,'waves.json','frozenWaves'),waveIds=new Set([...foundryWaveIds,...frozenWaveIds]);if(waveIds.size!==foundryWaveIds.size+frozenWaveIds.size)fail('waves.json','wave IDs must be globally unique');if(raw.waves.waves.length!==50)fail('waves.json','Foundry requires exactly 50 waves');raw.waves.waves.forEach((w,i)=>{if(w.number!==i+1)fail('waves.json',`${w.id} has invalid number`);if(w.compositionRuleId!==raw.waves.compositionRule.id)fail('waves.json',`${w.id} has unknown composition rule`)});raw.waves.frozenWaves.forEach((w,i)=>{if(w.number!==i+1)fail('waves.json',`${w.id} has invalid number`);array(w.composition,'waves.json',`${w.id}.composition`);const total=w.composition.reduce((sum,entry)=>{if(!orbIds.has(entry.orbId))fail('waves.json',`${w.id} references missing orb "${entry.orbId}"`);if(!Number.isInteger(entry.count)||entry.count<1)fail('waves.json',`${w.id} has invalid orb count`);return sum+entry.count},0);if(total!==w.orbCount)fail('waves.json',`${w.id} composition totals ${total}, expected ${w.orbCount}`)});
    const waveSetIds=ids(raw.waves.waveSets,'waves.json','waveSets');for(const set of raw.waves.waveSets){if(!mapIds.has(set.mapId))fail('waves.json',`${set.id} references missing map "${set.mapId}"`);array(set.waveIds,'waves.json',`${set.id}.waveIds`);if(set.waveIds.some(id=>!waveIds.has(id)))fail('waves.json',`${set.id} references a missing wave`);const map=raw.maps.maps.find(item=>item.id===set.mapId);if(set.waveIds.length!==map.totalWaves)fail('waves.json',`${set.id} must contain ${map.totalWaves} waves`)}for(const map of raw.maps.maps)if(!waveSetIds.has(map.waveSetId))fail('maps.json',`${map.id} references missing wave set "${map.waveSetId}"`);
    ids(raw.waves.specialWindows,'waves.json','specialWindows');ids(raw.waves.warnings,'waves.json','warnings');const finaleIds=ids(raw.waves.finales,'waves.json','finales');raw.waves.specialWindows.forEach(w=>{if(!orbIds.has(w.orbId))fail('waves.json',`${w.id} references missing orb "${w.orbId}"`)});raw.waves.finales.forEach(f=>{if(!bossIds.has(f.bossId))fail('waves.json',`${f.id} references missing boss`);f.encounterOrder.forEach(id=>{if(!orbIds.has(id))fail('waves.json',`${f.id} references missing orb "${id}"`)})});raw.waves.waves.forEach(w=>{if(w.finaleId&&!finaleIds.has(w.finaleId))fail('waves.json',`${w.id} references missing finale`)});
    const activeMap=raw.maps.maps.find(m=>m.id===raw.maps.defaultMapId),allWaves=[...raw.waves.waves,...raw.waves.frozenWaves],waveSets=index(raw.waves.waveSets);const config=Object.assign({},raw.maps.config,raw.orbs.config,raw.towers.config,raw.tutorial.config,raw.waves.config,raw.waves.runtimeConfig,{WORLD_WIDTH:activeMap.dimensions.width,WORLD_HEIGHT:activeMap.dimensions.height,CAMERA_SCROLL_SPEED:activeMap.cameraBounds.scrollSpeed,floorTileSize:activeMap.floor.tileSize,TOTAL_WAVES:activeMap.totalWaves,TRACK_WAYPOINTS:activeMap.trackWaypoints.map(({x,y})=>({x,y})),BOSS_ORB_TYPES:[],ADDITIONAL_ORB_TYPES:[]});
    ['startingCurrency','maximumHealth','startingHealth','waterElephantCost','TOTAL_WAVES','BALL_HEALTH','TIER0_ORB_HEALTH','BALL_SPEED','GAME_SPEEDS','FROST_SLOW_PER_STACK','FROST_SLOW_MAX_STACKS','FROST_SLOW_DURATION','FROST_SNOW_CAP_HEAL_PERCENT','FROST_SNOW_WEIGHT_SLOW_PER_HEAL','FROST_SNOW_WEIGHT_SPEED_FLOOR'].forEach(key=>{if(config[key]===undefined)fail('content configuration',`missing "${key}"`)});if(!(Number.isFinite(config.FROST_SLOW_PER_STACK)&&config.FROST_SLOW_PER_STACK>0&&config.FROST_SLOW_PER_STACK<=1))fail('content configuration','FROST_SLOW_PER_STACK must be between 0 and 1');if(!Number.isInteger(config.FROST_SLOW_MAX_STACKS)||config.FROST_SLOW_MAX_STACKS<1)fail('content configuration','FROST_SLOW_MAX_STACKS must be a positive integer');if(!(Number.isFinite(config.FROST_SLOW_DURATION)&&config.FROST_SLOW_DURATION>0))fail('content configuration','FROST_SLOW_DURATION must be positive');for(const key of ['FROST_SNOW_CAP_HEAL_PERCENT','FROST_SNOW_WEIGHT_SLOW_PER_HEAL','FROST_SNOW_WEIGHT_SPEED_FLOOR'])if(!(Number.isFinite(config[key])&&config[key]>0&&config[key]<=1))fail('content configuration',`${key} must be between 0 and 1`);
    const activeWaveSet=waveSets[activeMap.waveSetId],wavesByNumber=Object.fromEntries(activeWaveSet.waveIds.map(id=>{const wave=allWaves.find(item=>item.id===id);return[wave.number,wave]}));return deepFreeze(Object.assign({},raw,{config,activeMap,activeWaveSet,wavesByNumber,indexes:{maps:index(raw.maps.maps),orbs:index([...raw.orbs.normalTiers,...raw.orbs.specialOrbs,...raw.orbs.bosses]),towers:index(raw.towers.towers),achievements:index(raw.achievements.achievements),tutorial:index(raw.tutorial.steps),waves:index(allWaves),waveSets,difficulties:index(raw.difficulties.difficulties)},stableIds:{maps:[...mapIds],orbs:[...orbIds],towers:[...towerIds],achievements:[...achievementIds],tutorial:[...tutorialIds],waves:[...waveIds]}}));
  }
  const api={build};root.GameContentSchema=api;if(typeof module!=='undefined'&&module.exports)module.exports=api;
})(typeof globalThis!=='undefined'?globalThis:window);
