const assert=require('node:assert/strict');
const fs=require('node:fs');
const content=require('./test-content.js');
const schema=require('./content-schema.js');
assert.equal(content.activeMap.id,'map_foundry_sector_07');
assert.equal(content.maps.maps.length,2);
assert.equal(content.indexes.maps.frozen_expanse.totalWaves,20);
assert.equal(content.indexes.maps.map_foundry_sector_07.startingCurrency,100);
assert.equal(content.indexes.maps.frozen_expanse.startingCurrency,125);
assert.equal(content.indexes.maps.frozen_expanse.trackWaypoints.length,26);
assert.equal(content.indexes.maps.frozen_expanse.puddleEffects.snowMultiplier,.9);
assert.equal(content.indexes.maps.frozen_expanse.puddleEffects.iceMultiplier,1.15);
assert.equal(content.indexes.maps.frozen_expanse.puddleEffects.infoText,'Snow puddles slow orbs by 10%. Ice puddles speed up orbs by 15%.');
assert.equal(content.indexes.maps.frozen_expanse.snowMutation.id,'snow_covered');
assert.equal(content.indexes.maps.frozen_expanse.snowMutation.firstWave,14);
assert.equal(content.indexes.maps.frozen_expanse.snowMutation.spawnChance,.1);
assert.deepEqual(content.indexes.maps.frozen_expanse.snowMutation.attackIntervalSeconds,{min:5,max:10});
assert.equal(content.indexes.maps.frozen_expanse.snowMutation.resistanceRegenerationSeconds,120);
assert.equal(content.indexes.maps.frozen_expanse.snowMutation.frozenDurationSeconds,30);
assert.equal(content.indexes.maps.frozen_expanse.iceShield.id,'ice_shield');
assert.equal(content.indexes.maps.frozen_expanse.iceShield.firstWave,14);
assert.equal(content.indexes.maps.frozen_expanse.iceShield.spawnChance,.07);
assert.deepEqual(content.indexes.maps.frozen_expanse.iceShield.shieldHitRange,{min:1,max:5});
assert.equal(content.indexes.waveSets.frozen_waves.waveIds.length,20);
assert.equal(content.indexes.waves.frozen_wave_20.orbCount,32);
assert.equal(content.activeMap.trackWaypoints.length,22);
assert.equal(content.orbs.normalTiers.length,11);
assert.equal(content.towers.towers.length,11);
assert.equal(content.indexes.towers.flame_elephant.cost,225);
assert.equal(content.indexes.towers.flame_elephant.runtimeType,'flame');
assert.equal(content.indexes.towers.flame_elephant.baseStats.burnDuration,5);
assert.equal(content.indexes.towers.flame_elephant.baseStats.burnDamagePerTick,5.67);
assert.equal(content.indexes.towers.flame_elephant.upgrades.maxLevel,5);
assert.equal(content.indexes.towers.heater.cost,50);
assert.deepEqual(content.indexes.towers.heater.upgrades.radii,[115,150,190]);
assert.equal(content.achievements.achievements.length,11);
assert.equal(content.tutorial.steps.length,23);
assert.equal(content.waves.waves.length,50);
assert.deepEqual(content.waves.finales[0].encounterOrder.slice(-2),['tier_10','fused_prismatic_boss']);
assert.equal(content.indexes.orbs.fused_prismatic_boss.maxHp,10000);
assert.deepEqual(content.difficulties.difficulties.map(item=>item.id),['easy','normal','hard']);
assert.equal(content.indexes.difficulties.hard.elephantFinalDamageMultiplier,.93);
assert.equal(content.config.FROST_SLOW_PER_STACK,.05);
assert.equal(content.config.FROST_SLOW_MAX_STACKS,5);
assert.equal(content.config.FROST_SNOW_CAP_HEAL_PERCENT,.05);
assert.equal(content.config.FROST_SNOW_WEIGHT_SLOW_PER_HEAL,.02);
assert.equal(content.config.FROST_SNOW_WEIGHT_SPEED_FLOOR,.25);
const raw=Object.fromEntries(['maps','orbs','towers','achievements','tutorial','waves','difficulties'].map(name=>[name,JSON.parse(fs.readFileSync(`data/${name}.json`,'utf8'))]));
raw.maps.defaultMapId='frozen_expanse';
const frozenContent=schema.build(raw);
assert.equal(frozenContent.config.TOTAL_WAVES,20);
assert.equal(frozenContent.config.WORLD_HEIGHT,1780);
assert.equal(frozenContent.activeWaveSet.id,'frozen_waves');
assert.equal(frozenContent.wavesByNumber[20].id,'frozen_wave_20');
const gameplay=fs.readFileSync('./game.js','utf8');
const mapSystem=fs.readFileSync('./map-system.js','utf8');
assert.doesNotMatch(gameplay,/const CONFIG\s*=\s*Object\.freeze\(\{/);
assert.doesNotMatch(gameplay,/const TUTORIAL_STEPS\s*=\s*\[/);
assert.doesNotMatch(gameplay,/const ACHIEVEMENTS\s*=\s*Object\.freeze\(\[/);
assert.throws(()=>require('./content-schema.js').build({...content,maps:{...content.maps,defaultMapId:'missing_map'}}),/defaultMapId references missing map/);
const invalidMutation=structuredClone(raw);invalidMutation.maps.maps.find(map=>map.id==='frozen_expanse').snowMutation.spawnChance=1.1;
assert.throws(()=>require('./content-schema.js').build(invalidMutation),/spawnChance must be between 0 and 1/);
const invalidIceShield=structuredClone(raw);invalidIceShield.maps.maps.find(map=>map.id==='frozen_expanse').iceShield.shieldHitRange.max=4;
assert.throws(()=>require('./content-schema.js').build(invalidIceShield),/shieldHitRange must be exactly 1 through 5/);
assert.match(mapSystem,/OWNER_MAP_LAUNCH_KEY/);
assert.match(mapSystem,/verb==='\/win'/);
assert.match(mapSystem,/Map selection opened\./);
assert.match(mapSystem,/verb==='\/map'/);
assert.match(mapSystem,/Usage: \/map <foundry\|ice>/);
assert.match(mapSystem,/Unknown map\. Use: foundry or ice\./);
assert.match(mapSystem,/mapAliases=\{foundry:'map_foundry_sector_07',ice:'frozen_expanse'\}/);
assert.match(mapSystem,/ownerMapChooserOpen/);
assert.match(mapSystem,/puddleOrbSpeedBase=orbMovementSpeed/);
assert.match(mapSystem,/orb\.frozenPuddleType=puddle\?\.type\|\|null/);
assert.match(mapSystem,/puddleRules\.snowMultiplier/);
assert.match(mapSystem,/puddleRules\.iceMultiplier/);
assert.match(mapSystem,/validateFrozenPuddleLayout/);
assert.match(mapSystem,/drawOrbPuddleFeedback/);
assert.match(mapSystem,/let frozenSnowflakes=\[\]/);
assert.match(mapSystem,/function updateSnowfall/);
assert.match(mapSystem,/function drawSnowfall/);
assert.match(mapSystem,/prefersReducedMotion\(\)\?16:42/);
assert.match(mapSystem,/state\.paused/);
assert.match(mapSystem,/frozenSnowflakes=\[\]/);
assert.match(gameplay,/FROZEN_TRACK_PUDDLE_BLUEPRINTS/);
assert.match(gameplay,/randomizeFrozenTrackPuddles/);
assert.match(gameplay,/FROZEN_SCENERY_FOOTPRINTS/);
assert.match(gameplay,/pointOverlapsFrozenScenery/);
assert.match(gameplay,/sceneryPlacementBase=validPlacement/);
assert.match(gameplay,/scaleX/);
assert.match(gameplay,/scaleY/);
assert.match(gameplay,/edgeAmplitude/);
assert.match(gameplay,/puddleBlobPath/);
assert.match(gameplay,/drawBlobTexture/);
assert.match(gameplay,/drawFrozenTrack\(theme\)/);
assert.match(gameplay,/prefersReducedMotion\(\)/);
const snowMutation=fs.readFileSync('./snow-mutation.js','utf8');
const heater=fs.readFileSync('./heater.js','utf8');
assert.match(snowMutation,/function shouldSnowMutate/);
assert.match(snowMutation,/function applyFreezeHit/);
assert.match(snowMutation,/function updateTowerFreeze/);
assert.match(snowMutation,/function drawSnowCover/);
assert.match(snowMutation,/function drawFreezeBolts/);
assert.match(gameplay,/function applyFrostSlow/);
assert.match(gameplay,/function updateFrostSlowEffects/);
assert.match(snowMutation,/function activeFrostSlowStacks/);
assert.match(snowMutation,/frostStackSpeedBase=orbMovementSpeed/);
assert.match(snowMutation,/function applySnowCapFrostHeal/);
assert.match(snowMutation,/Snow Weight: \$\{weight\} heals/);
assert.match(heater,/function applyHeaterBacklash/);
assert.match(heater,/Heater Warmth: Level 1/);
assert.match(heater,/heaterRecoveryMultiplier/);
assert.match(snowMutation,/partitionFrozenTowers/);
assert.match(snowMutation,/function consumeIceShieldHit/);
assert.match(snowMutation,/function drawIceShield/);
assert.match(snowMutation,/DEBUG_MUTATIONS=Object\.freeze\(\['snowcap','iceshield'\]\)/);
assert.match(snowMutation,/Unknown mutation: \$\{mutation\}\. Available mutations: snowcap, iceshield\./);
assert.match(snowMutation,/Mutations available: snowcap, iceshield/);
assert.match(snowMutation,/override:mutation\|\|'none'/);
console.log('Content JSON validation tests passed.');
