const assert=require('node:assert/strict');
const fs=require('node:fs');
const content=require('./test-content.js');
const schema=require('./content-schema.js');
assert.equal(content.activeMap.id,'map_foundry_sector_07');
assert.equal(content.maps.maps.length,2);
assert.equal(content.indexes.maps.frozen_expanse.totalWaves,50);
assert.equal(content.indexes.maps.map_foundry_sector_07.startingCurrency,100);
assert.equal(content.indexes.maps.frozen_expanse.startingCurrency,135);
assert.equal(content.indexes.maps.frozen_expanse.trackWaypoints.length,26);
assert.equal(content.indexes.maps.frozen_expanse.puddleEffects.snowMultiplier,.9);
assert.equal(content.indexes.maps.frozen_expanse.puddleEffects.iceMultiplier,1.15);
assert.equal(content.indexes.maps.frozen_expanse.puddleEffects.infoText,'Snow puddles slow orbs by 10%. Ice puddles speed up orbs by 15%.');
assert.equal(content.indexes.maps.frozen_expanse.snowMutation.id,'snow_covered');
assert.equal(content.indexes.maps.frozen_expanse.snowMutation.firstWave,14);
assert.equal(content.indexes.maps.frozen_expanse.snowMutation.spawnChance,.1);
assert.deepEqual(content.indexes.maps.frozen_expanse.snowMutation.attackIntervalSeconds,{min:5,max:10});
assert.equal(content.indexes.maps.frozen_expanse.snowMutation.resistanceRegenerationSeconds,120);
assert.equal(content.indexes.maps.frozen_expanse.snowMutation.frozenDurationSeconds,30);
assert.equal(content.indexes.maps.frozen_expanse.iceShield.id,'ice_shield');
assert.equal(content.indexes.maps.frozen_expanse.iceShield.firstWave,14);
assert.equal(content.indexes.maps.frozen_expanse.iceShield.spawnChance,.07);
assert.deepEqual(content.indexes.maps.frozen_expanse.iceShield.shieldHitRange,{min:1,max:5});
assert.deepEqual(content.indexes.maps.frozen_expanse.iceMapRebalance,{nonBossHpMultiplier:.75,nonBossSpeedMultiplier:.9});
assert.equal(content.indexes.waveSets.frozen_waves.waveIds.length,50);
assert.equal(content.indexes.waves.frozen_wave_20.orbCount,24);
assert.equal(content.indexes.waves.frozen_wave_50.orbCount,22);
assert.deepEqual(content.waves.frozenWaves.slice(20).map(wave=>wave.orbCount),[25,25,27,29,28,29,29,29,29,31,31,31,31,31,32,33,33,32,32,35,29,28,28,28,14,17,19,20,21,22]);
assert.equal(content.config.GHOST_ORB_FIRST_WAVE,15);
assert.equal(content.config.SPECIAL_ORB_FIRST_ROUND,20);
assert.equal(content.config.fumeOrbFirstWave,25);
assert.equal(content.config.fumeOrbMutationChance,.25);
for(const wave of content.waves.frozenWaves)for(const entry of wave.composition){assert.notEqual(entry.variant,'ghost',`${wave.id} must use the shared Ghost Orb rules`);assert.ok(!['food_orb','fume_orb','engineer_orb'].includes(entry.orbId),`${wave.id} must use the shared special-orb rules`)}
for(const wave of content.waves.frozenWaves.slice(20))for(const entry of wave.composition){const orb=content.indexes.orbs[entry.orbId];if(orb.tier!==undefined)assert.ok(wave.number>=orb.introductionWave,`${wave.id} uses ${entry.orbId} before Wave ${orb.introductionWave}`)}
assert.equal(content.waves.waves.length,50);
assert.equal(content.waves.waves.at(-1).finaleId,'finale_prismatic_convergence');
assert.equal(content.activeMap.trackWaypoints.length,22);
assert.equal(content.orbs.normalTiers.length,11);
assert.equal(content.towers.towers.length,11);
assert.equal(content.indexes.towers.flame_elephant.cost,225);
assert.equal(content.indexes.towers.flame_elephant.runtimeType,'flame');
assert.equal(content.indexes.towers.flame_elephant.baseStats.burnDuration,5);
assert.equal(content.indexes.towers.flame_elephant.baseStats.burnDamagePerTick,5.67);
assert.equal(content.indexes.towers.flame_elephant.upgrades.maxLevel,5);
assert.equal(content.indexes.towers.heater.cost,50);
assert.deepEqual(content.indexes.towers.heater.upgrades.radii,[115,150,190]);
assert.equal(content.achievements.achievements.length,11);
assert.equal(content.tutorial.steps.length,23);
assert.deepEqual(content.waves.finales[0].encounterOrder.slice(-2),['tier_10','fused_prismatic_boss']);
assert.equal(content.indexes.orbs.fused_prismatic_boss.maxHp,10000);
assert.deepEqual(content.difficulties.difficulties.map(item=>item.id),['easy','normal','hard']);
assert.equal(content.indexes.difficulties.hard.elephantFinalDamageMultiplier,.93);
assert.equal(content.config.FROST_SLOW_PER_STACK,.05);
assert.equal(content.config.FROST_SLOW_MAX_STACKS,5);
assert.equal(content.config.FROST_SNOW_CAP_HEAL_PERCENT,.05);
assert.equal(content.config.FROST_SNOW_WEIGHT_SLOW_PER_HEAL,.02);
assert.equal(content.config.FROST_SNOW_WEIGHT_SPEED_FLOOR,.25);
const raw=Object.fromEntries(['maps','orbs','towers','achievements','tutorial','waves','difficulties'].map(name=>[name,JSON.parse(fs.readFileSync(`data/${name}.json`,'utf8'))]));
raw.maps.defaultMapId='frozen_expanse';
const frozenContent=schema.build(raw);
assert.equal(frozenContent.config.TOTAL_WAVES,50);
assert.equal(frozenContent.config.WORLD_HEIGHT,1780);
assert.equal(frozenContent.activeWaveSet.id,'frozen_waves');
assert.equal(frozenContent.wavesByNumber[20].id,'frozen_wave_20');
assert.equal(frozenContent.wavesByNumber[50].id,'frozen_wave_50');
const gameplay=fs.readFileSync('./game.js','utf8');
const mapSystem=fs.readFileSync('./map-system.js','utf8');
assert.doesNotMatch(gameplay,/const CONFIG\s*=\s*Object\.freeze\(\{/);
assert.doesNotMatch(gameplay,/const TUTORIAL_STEPS\s*=\s*\[/);
assert.doesNotMatch(gameplay,/const ACHIEVEMENTS\s*=\s*Object\.freeze\(\[/);
assert.throws(()=>require('./content-schema.js').build({...content,maps:{...content.maps,defaultMapId:'missing_map'}}),/defaultMapId references missing map/);
const invalidMutation=structuredClone(raw);invalidMutation.maps.maps.find(map=>map.id==='frozen_expanse').snowMutation.spawnChance=1.1;
assert.throws(()=>require('./content-schema.js').build(invalidMutation),/spawnChance must be between 0 and 1/);
const invalidIceShield=structuredClone(raw);invalidIceShield.maps.maps.find(map=>map.id==='frozen_expanse').iceShield.shieldHitRange.max=4;
assert.throws(()=>require('./content-schema.js').build(invalidIceShield),/shieldHitRange must be exactly 1 through 5/);
assert.match(mapSystem,/OWNER_MAP_LAUNCH_KEY/);
assert.match(mapSystem,/verb==='\/win'/);
assert.match(mapSystem,/Map selection opened\./);
assert.match(mapSystem,/verb==='\/map'/);
assert.match(mapSystem,/Usage: \/map <foundry\|ice>/);
assert.match(mapSystem,/const sharedSpecials=buildWaveBase\(wave\)\.filter\(marker=>marker\.ghost\|\|marker\.special\)/);
assert.match(mapSystem,/Unknown map\. Use: foundry or ice\./);
assert.match(mapSystem,/mapAliases=\{foundry:'map_foundry_sector_07',ice:'frozen_expanse'\}/);
assert.match(mapSystem,/function normalizeProfile/);
assert.match(mapSystem,/frozen\?\.completed&&\(frozen\.highestWave\|\|0\)<total/);
assert.match(mapSystem,/progress\.highestWave=map\.totalWaves/);
assert.match(mapSystem,/Frozen Expanse completed through Wave \$\{map\.totalWaves\}/);
assert.match(mapSystem,/ownerMapChooserOpen/);
assert.match(mapSystem,/puddleOrbSpeedBase=orbMovementSpeed/);
assert.match(mapSystem,/orb\.frozenPuddleType=puddle\?\.type\|\|null/);
assert.match(mapSystem,/puddleRules\.snowMultiplier/);
assert.match(mapSystem,/puddleRules\.iceMultiplier/);
assert.match(mapSystem,/function miniRobotPuddleType/);
assert.match(mapSystem,/root\.applyIceMapOrbRebalance=function/);
assert.match(mapSystem,/job\.spawnInterval=wave<=44\?1\.35:wave<=48\?1\.55:1\.65/);
assert.match(mapSystem,/puddleType==='snow'\?\.85:puddleType==='ice'\?1\.2:1/);
assert.match(mapSystem,/overlaps\.some\(puddle=>puddle\.type==='snow'\)/);
assert.match(mapSystem,/validateFrozenPuddleLayout/);
assert.match(mapSystem,/drawOrbPuddleFeedback/);
assert.match(mapSystem,/let frozenSnowflakes=\[\]/);
assert.match(mapSystem,/function updateSnowfall/);
assert.match(mapSystem,/function drawSnowfall/);
assert.match(mapSystem,/prefersReducedMotion\(\)\?16:42/);
assert.match(mapSystem,/state\.paused/);
assert.match(mapSystem,/frozenSnowflakes=\[\]/);
assert.match(gameplay,/FROZEN_TRACK_PUDDLE_BLUEPRINTS/);
assert.match(gameplay,/randomizeFrozenTrackPuddles/);
assert.match(gameplay,/FROZEN_SCENERY_FOOTPRINTS/);
assert.match(gameplay,/pointOverlapsFrozenScenery/);
assert.match(gameplay,/sceneryPlacementBase=validPlacement/);
assert.match(gameplay,/scaleX/);
assert.match(gameplay,/scaleY/);
assert.match(gameplay,/edgeAmplitude/);
assert.match(gameplay,/puddleBlobPath/);
assert.match(gameplay,/drawBlobTexture/);
assert.match(gameplay,/drawFrozenTrack\(theme\)/);
assert.match(gameplay,/prefersReducedMotion\(\)/);
const snowMutation=fs.readFileSync('./snow-mutation.js','utf8');
const heater=fs.readFileSync('./heater.js','utf8');
const iceOpening=fs.readFileSync('./ice-opening-cutscene.js','utf8');
const html=fs.readFileSync('./index.html','utf8');
const loader=fs.readFileSync('./data-loader.js','utf8');
assert.match(html,/id="iceOpeningCutscene"/);
assert.match(html,/id="skipIceOpeningCutscene"/);
assert.match(html,/id="ownerPasswordVisibility"[^>]*aria-label="Show password"/);
assert.match(html,/id="adminPasswordVisibility"[^>]*aria-label="Show password"/);
assert.match(loader,/'ice-opening-cutscene\.js'/);
assert.doesNotMatch(loader,/unplace-hold\.js/);
assert.match(html,/data-placement-card="elephant"/);
assert.doesNotMatch(html,/placementCancelHud|Hold 3 seconds/);
assert.doesNotMatch(html,/unplaceHint|Hold 3 seconds to unplace/);
assert.match(iceOpening,/const ICE_OPENING_SCENES=Object\.freeze/);
assert.match(iceOpening,/\{id:'freeze-result',duration:/);
assert.match(iceOpening,/The elephants are getting stronger\. We need an answer\./);
assert.match(iceOpening,/\{id:'shield-hit-one',duration:/);
assert.match(iceOpening,/\{id:'shield-hit-two',duration:/);
assert.match(iceOpening,/if\(state\)state\.paused=true/);
assert.match(iceOpening,/if\(runtime\.active\)\{updateIceOpening\(dt\);return\}/);
assert.match(iceOpening,/dataset\.action='replay-ice-opening'/);
assert.match(iceOpening,/captureGameplaySprite\(drawElephant/,'The opening captive must use the active Water Elephant renderer.');
assert.match(iceOpening,/captureGameplaySprite\(drawBall/,'The opening scientist must use the active orb renderer.');
assert.match(iceOpening,/INJECTION_PHASES=Object\.freeze/,'Every experiment must use the shared timed syringe sequence.');
assert.match(iceOpening,/elapsed<1\.5/,'The syringe must visibly insert and press before the subject reacts.');
assert.match(iceOpening,/runtime\.elapsed>=1\.8/,'Experiment reactions must wait for the serum delay.');
assert.match(iceOpening,/drawOpeningInjection\(rect,ratio,phase\)/,'The injection animation must render for every opening frame.');
assert.match(iceOpening,/PLATINUM_CUTSCENE_SCALE=5\.984/,'The opening scientist must retain the required close-up scale.');
assert.match(iceOpening,/captureGameplaySprite\(drawBall,orb,size,PLATINUM_CUTSCENE_SCALE\)/,'The large image must be rendered directly at cutscene resolution.');
assert.match(iceOpening,/drawBall,orb,size,PLATINUM_CUTSCENE_SCALE\),rect\.width\*\.54,rect\.height\*\.47\)/,'The larger scale must apply only to the cutscene scientist instance.');
assert.doesNotMatch(iceOpening,/function drawOpeningWaterElephant/,'No primitive cutscene elephant renderer may remain.');
assert.doesNotMatch(iceOpening,/function drawOpeningOrb/,'No primitive cutscene orb renderer may remain.');
assert.match(iceOpening,/mapGrid\?\.addEventListener\('click'/);
assert.match(snowMutation,/function shouldSnowMutate/);
assert.match(snowMutation,/function applyFreezeHit/);
assert.match(snowMutation,/function updateTowerFreeze/);
assert.match(snowMutation,/function drawSnowCover/);
assert.match(snowMutation,/function drawFreezeBolts/);
assert.match(gameplay,/function applyFrostSlow/);
assert.match(gameplay,/function miniRobotMovementSpeed/);
assert.match(gameplay,/iceMapBalanceApplied/);
assert.match(gameplay,/let left=miniRobotMovementSpeed\(mini\)\*dt/);
assert.match(gameplay,/function updateFrostSlowEffects/);
assert.match(snowMutation,/function activeFrostSlowStacks/);
assert.match(snowMutation,/frostStackSpeedBase=orbMovementSpeed/);
assert.match(snowMutation,/function applySnowCapFrostHeal/);
assert.match(snowMutation,/Snow Weight: \$\{weight\} heals/);
assert.match(heater,/function applyHeaterBacklash/);
assert.match(heater,/Heater Warmth: Level 1/);
assert.match(heater,/heaterRecoveryMultiplier/);
assert.match(snowMutation,/partitionFrozenTowers/);
assert.match(snowMutation,/function consumeIceShieldHit/);
assert.match(snowMutation,/function drawIceShield/);
assert.match(snowMutation,/DEBUG_MUTATIONS=Object\.freeze\(\['snowcap','iceshield'\]\)/);
assert.match(snowMutation,/Unknown mutation: \$\{mutation\}\. Available mutations: snowcap, iceshield\./);
assert.match(snowMutation,/Mutations available: snowcap, iceshield/);
assert.match(snowMutation,/override:mutation\|\|'none'/);
assert.doesNotMatch(snowMutation,/frostDamageText/,'Frost attacks must not render floating damage values.');
assert.doesNotMatch(snowMutation,/snowHealText/,'Snow-Cap healing must not render floating heal values.');
assert.match(snowMutation,/frostHitFlash/,'Normal Frost hits must use a short-lived local impact effect.');
assert.match(gameplay,/!shielded&&!snowCovered\)target\.frostHitFlash/,'Frost impacts must not imitate Ice Shield or Snow-Cap visuals.');
console.log('Content JSON validation tests passed.');
