/* Safe scientific currency for debug grants beyond JavaScript's numeric range. */
const LARGE_CURRENCY_MAX_EXPONENT='1000000000000000',LARGE_CURRENCY_SENTINEL=1e308;
function canonicalExponent(raw){const clean=String(raw||'');if(!/^\d+$/.test(clean))return null;return clean.replace(/^0+(?=\d)/,'')||'0'}
function exponentWithinLimit(exponent){return exponent.length<LARGE_CURRENCY_MAX_EXPONENT.length||(exponent.length===LARGE_CURRENCY_MAX_EXPONENT.length&&exponent<=LARGE_CURRENCY_MAX_EXPONENT)}
function exponentCompare(left,right){return left.length-right.length||left.localeCompare(right)}
function parseSafeCurrencyAmount(source){const value=String(source||'');let match=value.match(/^10\^(\d+)$/i);if(match){const exponent=canonicalExponent(match[1]);return exponentWithinLimit(exponent)?{mantissa:1,exponent}:{error:`Exponent is too large. Maximum supported exponent is ${LARGE_CURRENCY_MAX_EXPONENT}.`}}match=value.match(/^([0-9]+(?:\.[0-9]+)?|\.[0-9]+)(?:e\+?(\d+))?$/i);if(!match)return{error:'Invalid amount. Use a non-negative value, scientific notation (1e50), or 10^N.'};const mantissa=Number(match[1]),exponent=canonicalExponent(match[2]||'0');if(!Number.isFinite(mantissa)||mantissa<0)return{error:'Currency amount must be non-negative.'};return exponentWithinLimit(exponent)?{mantissa,exponent}:{error:`Exponent is too large. Maximum supported exponent is ${LARGE_CURRENCY_MAX_EXPONENT}.`}}
function currencyScientificText(value){return `${Number(value.mantissa.toPrecision(12))}e+${value.exponent}`}
function addSafeCurrency(amount){if(amount.exponent==='0'&&amount.mantissa<1e15&&!state.currencyScientific){state.currency+=amount.mantissa;return}const current=state.currencyScientific;if(!current){state.currencyScientific={mantissa:amount.mantissa,exponent:amount.exponent};state.currency=LARGE_CURRENCY_SENTINEL;return}const comparison=exponentCompare(current.exponent,amount.exponent);if(comparison===0)current.mantissa+=amount.mantissa;else if(comparison<0)state.currencyScientific={mantissa:amount.mantissa,exponent:amount.exponent}}
const formatLargeCurrencyBase=formatCurrency;formatCurrency=function(value){return value===state?.currency&&state.currencyScientific?currencyScientificText(state.currencyScientific):formatLargeCurrencyBase(value)};
function grantDebugCurrency(source,write){const amount=parseSafeCurrencyAmount(source);if(amount.error){write(amount.error,'error');return}const before=formatCurrency(state.currency);addSafeCurrency(amount);updateUI();write(`Currency: ${before} → ${formatCurrency(state.currency)}.`,'success')}
const ownerCurrencyCommandBase=executeDebugCommand;executeDebugCommand=function(source){const parts=String(source||'').trim().split(/\s+/);if(parts[0]?.toLowerCase()==='/money'){if(parts.length!==2){debugWrite('Usage: /money <amount>.','error');return}grantDebugCurrency(parts[1],debugWrite);return}return ownerCurrencyCommandBase(source)};
const adminCurrencyCommandBase=executeAdminDebugCommand;executeAdminDebugCommand=function(source){const parts=String(source||'').trim().split(/\s+/);if(parts[0]?.toLowerCase()==='/money'){if(parts.length!==2){adminDebugWrite('Usage: /money <amount>.','error');return}grantDebugCurrency(parts[1],adminDebugWrite);return}return adminCurrencyCommandBase(source)};
const currencySnapshotBase=finaleRunSnapshot;finaleRunSnapshot=function(){const snapshot=currencySnapshotBase();if(state.currencyScientific)snapshot.currencyScientific={...state.currencyScientific};return snapshot};
const currencyRestoreBase=restoreFinaleSave;restoreFinaleSave=function(saved){const restored=currencyRestoreBase(saved);if(restored&&saved?.run?.currencyScientific){state.currencyScientific={...saved.run.currencyScientific};state.currency=LARGE_CURRENCY_SENTINEL;updateUI()}return restored};
