/* Engineer Orbs travel to, visibly dig, and then create a floor-system hole. */
function engineerDigTarget(){const tiles=state.floorTiles||[];const candidates=tiles.filter(tile=>tile.level!==2).concat(tiles.filter(tile=>tile.level===2));if(candidates.length)return candidates[0];for(let tries=0;tries<40;tries++){const point=floorTileAt({x:gameRandom()*CONFIG.WORLD_WIDTH,y:gameRandom()*CONFIG.WORLD_HEIGHT},true);if(point)return point}return null}
const engineerDigCreateBase=createEngineerHole;
createEngineerHole=function(orb){if(orb?.specialType!=='engineer'||orb.digState)return engineerDigCreateBase(orb);const tile=engineerDigTarget();if(!tile)return;orb.digState='travel';orb.digTarget={x:tile.x,y:tile.y,key:tile.key,level:tile.level||0,mineLevel:tile.mineLevel||0};orb.digElapsed=0;orb.digInvincible=true;orb.state='digging';orb.targetable=true};
function engineerDigComplete(orb){const target=orb.digTarget,tile=(state.floorTiles||[]).find(item=>item.key===target.key)||target;if(tile.level===2){const strong=(tile.mineLevel||1)===2;orb.digMineExplosion=true;consumeLandmine(tile);burst(tile.x,tile.y,'#fff6b0',58,255);for(let i=0;i<3;i++)burst(tile.x+(i-1)*12,tile.y-8,'#59646a',10,75);if(strong)for(const nearby of state.balls.filter(item=>item!==orb&&item.targetable&&dist(item,tile)<=CONFIG.landmineBlastRadius).sort((a,b)=>dist(a,tile)-dist(b,tile)).slice(0,2))damageOrbFromLevelTwoMine(nearby,tile);defeatSpecial(orb);unlockAchievement('engineer-mine');return}const hole={x:tile.x,y:tile.y,radius:CONFIG.engineerHoleRadius,orb,repairing:false,repairLife:0,fallingTower:null,square:true};(state.engineerHoles||(state.engineerHoles=[])).push(hole);orb.engineerHole=hole;tile.damage=0;orb.digState='pop';orb.digElapsed=0;orb.digInvincible=false;burst(tile.x,tile.y,'#5c4636',22,110)}
const engineerDigUpdateBase=update;
update=function(dt){engineerDigUpdateBase(dt);for(const orb of [...state.balls]){if(orb.specialType!=='engineer'||!orb.digState)continue;const target=orb.digTarget;if(orb.digState==='travel'){const dx=target.x-orb.x,dy=target.y-orb.y,d=Math.hypot(dx,dy),step=150*dt;if(d>step){orb.x+=dx/d*step;orb.y+=dy/d*step}else{orb.x=target.x;orb.y=target.y;orb.digState='swing';orb.digElapsed=0}}else if(orb.digState==='swing'){orb.digElapsed+=dt;if(orb.digElapsed>=1.5)engineerDigComplete(orb)}else if(orb.digState==='pop'){orb.digElapsed+=dt;if(orb.digElapsed>=.45){orb.digState=null;orb.digInvincible=false;orb.state='active';orb.seg=Math.max(0,path.findIndex(point=>Math.hypot(point.x-orb.x,point.y-orb.y)<80));if(orb.seg<0)orb.seg=0}}}};
const engineerDigHitBase=hitOrb;
hitOrb=function(tower,target){if(target?.specialType==='engineer'&&target.digInvincible)return;return engineerDigHitBase(tower,target)};
const engineerDigDefeatBase=defeatSpecial;
defeatSpecial=function(orb,...args){if(orb?.specialType==='engineer'&&orb.digInvincible&&!orb.digMineExplosion)return;return engineerDigDefeatBase(orb,...args)};
const engineerDigDrawBase=drawSpecialBall;
drawSpecialBall=function(orb){engineerDigDrawBase(orb);if(orb?.specialType!=='engineer'||!orb.digState)return;const target=orb.digTarget;ctx.save();ctx.translate(target.x,target.y);if(orb.digState==='swing'){const crack=Math.min(1,orb.digElapsed/1.5);ctx.strokeStyle='#c78c55';ctx.lineWidth=2+crack*2;ctx.beginPath();ctx.moveTo(-18,-16);ctx.lineTo(-4,-3);ctx.lineTo(9,13);ctx.moveTo(17,-15);ctx.lineTo(3,-2);ctx.lineTo(-10,15);ctx.stroke();ctx.fillStyle='#c7a16a';for(let i=0;i<5;i++){const a=i*1.25+state.gameTime*8,r=12+crack*16;ctx.fillRect(Math.cos(a)*r-2,Math.sin(a)*r-2,4,4)}}ctx.strokeStyle='#e4e9de';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(9,-18);ctx.lineTo(26,-31+Math.sin(state.gameTime*14)*8);ctx.stroke();ctx.restore()};
const engineerDigGroundBase=drawGround;
drawGround=function(){engineerDigGroundBase();for(const hole of state.engineerHoles||[]){if(!hole.square)continue;ctx.save();ctx.fillStyle='#24180f';ctx.fillRect(hole.x-22,hole.y-22,44,44);ctx.strokeStyle='#a97545';ctx.lineWidth=2;ctx.strokeRect(hole.x-22,hole.y-22,44,44);ctx.restore()}};
