// Multi-map profile, selection, map-scoped waves, and resumable per-map runs.
(function(root){
  'use strict';
  const content=root.GameContent,map=content.activeMap,PROFILE_KEY='elephant-track-profile-v1',RUN_PREFIX='elephant-track-run-v1',OWNER_MAP_LAUNCH_KEY='elephant-track-owner-map-launch-v1';
  function freshProfile(){return{version:1,selectedMapId:'map_foundry_sector_07',unlockedMapIds:['map_foundry_sector_07'],maps:{}}}
  function readProfile(){try{const value=JSON.parse(localStorage.getItem(PROFILE_KEY)||'null');return value&&value.version===1?{...freshProfile(),...value,maps:value.maps||{},unlockedMapIds:Array.isArray(value.unlockedMapIds)?value.unlockedMapIds:['map_foundry_sector_07']}:freshProfile()}catch{return freshProfile()}}
  let profile=readProfile(),ownerMapChooserOpen=false;
  function takeOwnerMapLaunch(){try{const launch=JSON.parse(localStorage.getItem(OWNER_MAP_LAUNCH_KEY)||'null');localStorage.removeItem(OWNER_MAP_LAUNCH_KEY);return launch?.mapId===map.id?launch:null}catch{return null}}
  const ownerMapLaunch=takeOwnerMapLaunch();
  function writeProfile(){localStorage.setItem(PROFILE_KEY,JSON.stringify(profile))}
  function mapProgress(id){return profile.maps[id]||(profile.maps[id]={highestWave:0,completed:false,lastDifficulty:'normal',activeRunKey:null})}
  function unlocked(id){return id==='map_foundry_sector_07'||profile.unlockedMapIds.includes(id)}
  function unlockFrozen(){if(!profile.unlockedMapIds.includes('frozen_expanse'))profile.unlockedMapIds.push('frozen_expanse');writeProfile();renderMapSelection();return true}
  function activeRunKey(difficulty=difficultyKey()){return`${RUN_PREFIX}:${map.id}:${difficulty}`}
  function waveDefinition(number){return content.wavesByNumber[number]}
  const ballsForMapBase=ballsForWave;ballsForWave=function(wave){return waveDefinition(wave)?.orbCount??ballsForMapBase(wave)};
  const buildWaveBase=buildWaveSequence;buildWaveSequence=function(wave){const definition=waveDefinition(wave);if(map.id!=='frozen_expanse'||!definition?.composition)return buildWaveBase(wave);const sequence=[];for(const entry of definition.composition){const orb=content.indexes.orbs[entry.orbId];for(let i=0;i<entry.count;i++){if(orb.type)sequence.push({contentId:entry.orbId,special:true,specialType:orb.type,ghost:false});else sequence.push({contentId:entry.orbId,special:false,tier:orb.tier,ghost:entry.variant==='ghost'})}}const random=seededGenerator(state.specialSeed^Math.imul(wave,2654435761));for(let i=sequence.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[sequence[i],sequence[j]]=[sequence[j],sequence[i]]}return sequence};
  // Puddles are visual map objects, but their speed modifier is calculated
  // here at movement time.  This keeps every pre-existing orb modifier first
  // and never writes to an orb's base/original speed.
  const puddleRules=map.puddleEffects;
  function puddleCenter(puddle){const a=path[puddle.segment],b=path[puddle.segment+1],vector=frozenSegmentVector(a,b);return{x:a.x+vector.dx*puddle.at+vector.nx*puddle.offset,y:a.y+vector.dy*puddle.at+vector.ny*puddle.offset}}
  function orbInsidePuddle(orb,puddle){const center=puddleCenter(puddle),angle=puddle.angle||0,cos=Math.cos(angle),sin=Math.sin(angle),dx=orb.x-center.x,dy=orb.y-center.y,localX=dx*cos+dy*sin,localY=-dx*sin+dy*cos,scale=puddle.scale||1,rx=25*scale,ry=12*scale,normal=Math.hypot(localX/rx,localY/ry),direction=Math.atan2(localY/ry,localX/rx),irregularEdge=.9+.1*Math.sin(direction*3+puddle.segment*.7);return normal<=irregularEdge}
  function puddleForOrb(orb){if(map.id!=='frozen_expanse'||orb?.isBoss)return null;return FROZEN_TRACK_PUDDLES.find(puddle=>orbInsidePuddle(orb,puddle))||null}
  function validateFrozenPuddleLayout(){if(map.id!=='frozen_expanse')return;for(let a=0;a<FROZEN_TRACK_PUDDLES.length;a++)for(let b=a+1;b<FROZEN_TRACK_PUDDLES.length;b++){const first=FROZEN_TRACK_PUDDLES[a],second=FROZEN_TRACK_PUDDLES[b],one=puddleCenter(first),two=puddleCenter(second),safeDistance=27*(first.scale||1)+27*(second.scale||1);if(Math.hypot(one.x-two.x,one.y-two.y)<safeDistance)throw new Error('Frozen Expanse puddles overlap; snow and ice effects must remain exclusive.')}}
  validateFrozenPuddleLayout();
  const puddleOrbSpeedBase=orbMovementSpeed;orbMovementSpeed=function(orb){const speed=puddleOrbSpeedBase(orb),puddle=puddleForOrb(orb);orb.frozenPuddleType=puddle?.type||null;if(!puddle)return speed;return speed*(puddle.type==='snow'?puddleRules.snowMultiplier:puddleRules.iceMultiplier)};
  function drawOrbPuddleFeedback(orb){const type=orb?.frozenPuddleType;if(!type)return;ctx.save();ctx.translate(orb.x,orb.y+13);if(type==='snow'){ctx.globalAlpha=.58;ctx.fillStyle='#f7fdff';for(const offset of [-9,0,9]){ctx.beginPath();ctx.ellipse(offset,3+Math.abs(offset)*.08,3.4,1.8,0,0,Math.PI*2);ctx.fill()}ctx.strokeStyle='#b7d0d8';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(-12,6);ctx.lineTo(12,6);ctx.stroke()}else{ctx.globalAlpha=prefersReducedMotion()?.45:.42+.14*Math.sin(state.gameTime*9+orb.id);ctx.strokeStyle='#a9f4ff';ctx.shadowColor='#72e9ff';ctx.shadowBlur=7;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(-18,5);ctx.quadraticCurveTo(-4,-1,15,4);ctx.stroke();ctx.globalAlpha*=.62;ctx.beginPath();ctx.moveTo(-25,9);ctx.quadraticCurveTo(-8,4,7,8);ctx.stroke()}ctx.restore()}
  const puddleDrawBallBase=drawBall;drawBall=function(orb){drawOrbPuddleFeedback(orb);return puddleDrawBallBase(orb)};
  const warningBase=warningLinesForSequence;warningLinesForSequence=function(sequence,wave){if(map.id!=='frozen_expanse')return warningBase(sequence,wave);const seen=state.specialWarningsSeen||(state.specialWarningsSeen={ghost:false,food:false,fume:false}),lines=[];if(!seen.ghost&&sequence.some(x=>x.ghost))lines.push({type:'ghost',text:'Ghost Orbs incoming — only Ghost-capable defenders can see them.'});if(!seen.food&&sequence.some(x=>x.specialType==='food'))lines.push({type:'food',text:'Food Orbs incoming — nearby eligible elephants may be lured away.'});if(!seen.fume&&sequence.some(x=>x.specialType==='fume'||x.specialType==='engineer'))lines.push({type:'fume',text:'Fume and Engineer Orbs incoming — prepare immune defenders and floor management.'});return lines};
  document.querySelector('#mapEyebrow').textContent=map.name.toUpperCase();document.body.dataset.mapTheme=map.theme.id;
  document.querySelectorAll('#difficultyModal [data-difficulty]').forEach(button=>{const rule=content.indexes.difficulties[button.dataset.difficulty],span=button.querySelector('span');if(span)span.textContent=rule.displayText});
  const selector=document.querySelector('#mapSelectionModal'),grid=document.querySelector('#mapSelectionGrid'),mapButton=document.querySelector('#mapSelectionButton'),chooseMapBanner=document.querySelector('#chooseMapBanner');
  function renderMapSelection(){profile=readProfile();grid.innerHTML=content.maps.maps.map(item=>{const progress=mapProgress(item.id),normallyUnlocked=unlocked(item.id),isUnlocked=normallyUnlocked||ownerMapChooserOpen,difficulty=content.indexes.difficulties[progress.lastDifficulty]||content.indexes.difficulties.normal,status=progress.completed?'COMPLETE':normallyUnlocked?'AVAILABLE':ownerMapChooserOpen?'OWNER ACCESS':'LOCKED',puddleInfo=item.puddleEffects?`<p class="map-puddle-info">${item.puddleEffects.infoText}</p>`:'';return`<article class="map-card ${isUnlocked?'':'locked'} ${item.theme.id}"><div class="map-preview" aria-label="${item.name} preview"><i></i><b></b><span></span></div><div class="map-card-copy"><small>${item.totalWaves} WAVES</small><h3>${item.name}</h3><p>${item.description}</p>${puddleInfo}<dl><div><dt>HIGHEST WAVE</dt><dd>${progress.highestWave||0} / ${item.totalWaves}</dd></div><div><dt>STATUS</dt><dd>${status}</dd></div><div><dt>DIFFICULTY</dt><dd>${difficulty.name.toUpperCase()}</dd></div></dl><div class="difficulty-meter" data-difficulty="${difficulty.id}"><span>EASY</span><span>NORMAL</span><span>HARD</span></div>${!normallyUnlocked&&!ownerMapChooserOpen?`<em>Complete Foundry Sector 07 and defeat its final boss to unlock.</em>`:''}<button type="button" data-play-map="${item.id}" ${isUnlocked?'':'disabled'}>${isUnlocked?'PLAY':'LOCKED'}</button></div></article>`}).join('');grid.querySelectorAll('[data-play-map]').forEach(button=>button.addEventListener('click',()=>selectMap(button.dataset.playMap)))}
  function openMapSelection(options={}){ownerMapChooserOpen=!!options.owner;renderMapSelection();selector.classList.remove('hidden')}
  function closeMapSelection(){selector.classList.add('hidden');ownerMapChooserOpen=false}
  function unfinishedRun(){return state?.status==='playing'&&(state.wave>0||state.towers.length||state.papayas.length||state.goldenPapayas.length)}
  function pauseForOwnerMapChoice(){if(!state)return;saveRun();state.manualPaused=true;state.paused=true;state.pendingWaveStart=null;warningUI.modal.classList.add('hidden');ui.pauseGame.textContent='RESUME';ui.pausedLabel.classList.remove('hidden')}
  function discardRuntimeForMapSwitch(){if(!state)return;state.ownerMapTransition=true;clearDebugOrbs();state.waveJobs=[];state.pendingWaveRewards=[];state.pendingWaveStart=null;state.autoCountdown=null;state.miniRobots=[];state.miniRobotEffects=[];state.engineerHoles=[];state.floorTiles=[];sprays=[];particles=[];splashPulses=[];currencyLights=[];knowledgeLights=[];destructionEffects=[];clearFinalePresentation?.()}
  function beginOwnerMapLoad(id,confirmSwitch){if(!content.indexes.maps[id])return false;if(confirmSwitch&&state?.status==='playing'&&!confirm('Switch maps? Your current run will be replaced.'))return false;pauseForOwnerMapChoice();discardRuntimeForMapSwitch();const targetProgress=mapProgress(id);targetProgress.activeRunKey=null;profile.selectedMapId=id;writeProfile();localStorage.setItem(OWNER_MAP_LAUNCH_KEY,JSON.stringify({mapId:id,requestedAt:Date.now()}));location.reload();return true}
  function selectMap(id){if(ownerMapChooserOpen)return beginOwnerMapLoad(id,false);if(!unlocked(id))return;if(id!==map.id&&unfinishedRun()&&!confirm(`Leave the unfinished ${map.name} run? It will remain saved separately.`))return;profile.selectedMapId=id;writeProfile();location.reload()}
  mapButton.addEventListener('click',openMapSelection);chooseMapBanner.addEventListener('click',openMapSelection);document.querySelector('#closeMapSelection').addEventListener('click',closeMapSelection);selector.addEventListener('click',event=>{if(event.target===selector)closeMapSelection()});mapButton.classList.toggle('hidden',!unlocked('frozen_expanse'));
  function towerSnapshot(t){return finaleTowerSnapshot(t)}
  function safeHole(hole){return{key:hole.key,x:hole.x,y:hole.y,radius:hole.radius,square:!!hole.square,repairing:false,repairLife:0}}
  function snapshotRun(){return{version:1,mapId:map.id,difficulty:difficultyKey(),savedAt:Date.now(),state:{currency:state.currency,currencyScientific:state.currencyScientific||null,currentHealth:state.currentHealth,maximumHealth:state.maximumHealth,wave:state.wave,startingWave:state.startingWave,waveJobs:state.waveJobs.map(job=>({...job,spawnSequence:(job.spawnSequence||[]).map(marker=>({...marker}))})),specialWindows:state.specialWindows,fumeWindows:state.fumeWindows,specialWarningsSeen:state.specialWarningsSeen,specialSeed:state.specialSeed,randomState:state.randomState,nextTowerId:state.nextTowerId,stats:state.stats,starterGift:state.starterGift,cameraX:state.cameraX,cameraY:state.cameraY,towers:state.towers.filter(t=>!t.sold).map(towerSnapshot),papayas:state.papayas.filter(t=>!t.sold),goldenPapayas:state.goldenPapayas.filter(t=>!t.sold),balls:state.balls.map(finaleOrbSnapshot),floorTiles:state.floorTiles||[],engineerHoles:(state.engineerHoles||[]).map(safeHole)}}}
  function saveRun(){if(state?.ownerMapTransition||!state?.difficultyLocked||state.status!=='playing')return;const key=activeRunKey();localStorage.setItem(key,JSON.stringify(snapshotRun()));const progress=mapProgress(map.id);progress.activeRunKey=key;progress.lastDifficulty=difficultyKey();progress.highestWave=Math.max(progress.highestWave||0,state.wave||0);writeProfile()}
  function clearRun(){const progress=mapProgress(map.id);if(progress.activeRunKey)localStorage.removeItem(progress.activeRunKey);progress.activeRunKey=null;writeProfile()}
  function restoreRun(){const progress=mapProgress(map.id),key=progress.activeRunKey;if(!key)return false;let saved;try{saved=JSON.parse(localStorage.getItem(key)||'null')}catch{return false}if(!saved||saved.mapId!==map.id||saved.version!==1)return false;const s=saved.state||{};Object.assign(state,{currency:s.currency??state.currency,currencyScientific:s.currencyScientific||null,currentHealth:s.currentHealth??state.currentHealth,maximumHealth:s.maximumHealth??state.maximumHealth,wave:s.wave||0,startingWave:s.startingWave||1,waveJobs:s.waveJobs||[],specialWindows:s.specialWindows||{},fumeWindows:s.fumeWindows||{},specialWarningsSeen:s.specialWarningsSeen||{ghost:false,food:false,fume:false},specialSeed:s.specialSeed??state.specialSeed,randomState:s.randomState??state.randomState,nextTowerId:s.nextTowerId||1,stats:s.stats||state.stats,starterGift:s.starterGift||state.starterGift,cameraX:s.cameraX||0,cameraY:s.cameraY||0,towers:(s.towers||[]).map(restoreFinaleTower),papayas:(s.papayas||[]).map(x=>({...x})),goldenPapayas:(s.goldenPapayas||[]).map(x=>({...x})),balls:(s.balls||[]).map(x=>({...x,attracted:[]})),floorTiles:(s.floorTiles||[]).map(x=>({...x})),engineerHoles:(s.engineerHoles||[]).map(x=>({...x}))});state.difficulty=content.indexes.difficulties[saved.difficulty]?saved.difficulty:'normal';state.difficultyLocked=true;hideDifficultyChoice();renderDifficultyHud();resizeGameViewport();updateUI();return true}
  const beginWaveMapBase=beginWave;beginWave=function(wave,sequence){beginWaveMapBase(wave,sequence);const progress=mapProgress(map.id);progress.highestWave=Math.max(progress.highestWave||0,wave);progress.lastDifficulty=difficultyKey();writeProfile();saveRun()};
  const setDifficultyMapBase=setRunDifficulty;setRunDifficulty=function(key){setDifficultyMapBase(key);if(state.difficultyLocked){mapProgress(map.id).lastDifficulty=key;writeProfile();saveRun()}};
  const completeFinalMapBase=completeFinalEncounter;completeFinalEncounter=function(){const wasComplete=state.finale?.phase==='complete';completeFinalMapBase();if(!wasComplete&&state.finale?.phase==='complete'){const progress=mapProgress('map_foundry_sector_07');progress.completed=true;progress.highestWave=50;unlockFrozen();clearRun();mapButton.classList.remove('hidden');chooseMapBanner.classList.remove('hidden');chooseMapBanner.textContent='CHOOSE MAP / PLAY AGAIN'}};
  const finishMapBase=finish;finish=function(kind){finishMapBase(kind);if(kind==='won'&&map.id==='frozen_expanse'){const progress=mapProgress(map.id);progress.completed=true;progress.highestWave=20;progress.lastDifficulty=difficultyKey();writeProfile();clearRun();const h=ui.banner.querySelector('h2'),p=ui.banner.querySelector('p');h.textContent='FROZEN EXPANSE COMPLETE';p.textContent='More frozen waves are coming in a future update.';chooseMapBanner.classList.remove('hidden');chooseMapBanner.textContent='CHOOSE MAP';ui.bannerRestart.textContent='PLAY AGAIN'}else if(kind==='lost')clearRun()};
  const ownerMapCommandBase=executeDebugCommand;executeDebugCommand=function(source){const command=source.trim(),parts=command.split(/\s+/),verb=parts[0]?.toLowerCase(),mapName=parts[1]?.toLowerCase(),mapAliases={foundry:'map_foundry_sector_07',ice:'frozen_expanse'};if(verb==='/win'&&parts.length===1){pauseForOwnerMapChoice();debugWrite('Map selection opened.','success');closeDebugConsole();openMapSelection({owner:true});showEncyclopediaNotice('Map selection opened.');return}if(verb==='/map'){if(parts.length===1){debugWrite('Usage: /map <foundry|ice>','error');return}if(parts.length!==2||!mapAliases[mapName]){debugWrite('Unknown map. Use: foundry or ice.','error');return}beginOwnerMapLoad(mapAliases[mapName],true);return}if(command.toLowerCase()==='/unlock frozen'){unlockFrozen();mapButton.classList.remove('hidden');debugWrite('Frozen Expanse unlocked for this profile.','success');return}if(command.toLowerCase()==='/help'){ownerMapCommandBase(source);debugWrite('/win — Opens map selection.\n/map <foundry|ice> — Opens a specific map.\n/unlock frozen — Permanently unlock Frozen Expanse.','success');return}return ownerMapCommandBase(source)};
  window.addEventListener('pagehide',saveRun);if(typeof setInterval==='function')setInterval(saveRun,3000);
  if(ownerMapLaunch){
    // Owner map commands deliberately begin a fresh run on the selected map.
    // Existing saves for other maps remain untouched.
    clearDifficultyRun();state.difficulty=null;state.difficultyLocked=false;
    hideDifficultyChoice();renderDifficultyHud();updateUI();
  }else restoreRun();
})(globalThis);
